---
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_keyring_path: /etc/apt/keyrings/docker.asc
docker_apt_uri: https://download.docker.com/linux/ubuntu
docker_apt_suite_map:
  "26.04": noble
docker_apt_suite: "{{ docker_apt_suite_map.get(ansible_facts['distribution_version'], ansible_facts['distribution_release']) }}"
docker_apt_components:
  - stable

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_service_name: docker
docker_users: []

docker_apt_architecture_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

docker_apt_architecture: "{{ docker_apt_architecture_map.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
