---
all:
  vars:
    ansible_user: ubuntu
    pocket_network: beta
    pocket_chain_id: pocket-lego-testnet
    pocket_rpc_url: https://replace-me.example.com
    pocket_grpc_address: replace-me.example.com:443

    igniter_provider_enabled: true
    igniter_middleman_enabled: false
    ha_relayminer_enabled: true

  children:
    provider_hosts:
      hosts: {}
    middleman_hosts:
      hosts: {}
    postgres_hosts:
      hosts: {}
    temporal_hosts:
      hosts: {}
    redis_hosts:
      hosts: {}
    relay_relayers:
      hosts: {}
    relay_miners:
      hosts: {}
    reverse_proxy_hosts:
      hosts: {}
    pocket_cli_hosts:
      hosts: {}
