---
all:
  vars:
    ansible_user: ubuntu
    pocket_network: main
    pocket_chain_id: pocket
    pocket_rpc_url: https://sauron-rpc.infra.pocket.network
    pocket_grpc_address: sauron-grpc.infra.pocket.network:443

    igniter_provider_enabled: true
    igniter_middleman_enabled: false
    ha_relayminer_enabled: true

    provider_domain: provider.example.com
    provider_public_api_domain: provider-api.example.com
    relay_public_domain: relayer.example.com

    postgres_deployment_mode: docker
    temporal_deployment_mode: docker
    redis_deployment_mode: docker

    igniter_provider_owner_identity: pokt1replacewithowneraddress
    igniter_provider_owner_email: ops@example.com
    igniter_provider_app_identity: VAULT_OR_SECRET_MANAGER_VALUE

  children:
    provider_hosts:
      hosts:
        pocket-provider-01:
          ansible_host: 192.0.2.20
    middleman_hosts:
      hosts: {}
    postgres_hosts:
      hosts:
        pocket-provider-01:
    temporal_hosts:
      hosts:
        pocket-provider-01:
    redis_hosts:
      hosts:
        pocket-provider-01:
    relay_relayers:
      hosts:
        pocket-provider-01:
    relay_miners:
      hosts:
        pocket-provider-01:
    reverse_proxy_hosts:
      hosts:
        pocket-provider-01:
    pocket_cli_hosts:
      hosts:
        pocket-provider-01:
